name: SonarCloud Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            
      - name: Generate and post detailed metrics comment
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # 現在のPull Requestのメトリクスを取得
          CURRENT_METRICS=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/measures/component?component=${PROJECT_KEY}&metricKeys=complexity,cognitive_complexity&pullRequest=${PULL_REQUEST_NUMBER}" | jq -r '.component.measures')
          
          # ターゲットブランチ（通常はmain）のメトリクスを取得
          TARGET_METRICS=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/measures/component?component=${PROJECT_KEY}&metricKeys=complexity,cognitive_complexity" | jq -r '.component.measures')
          
          # 差分を計算
          CYCLO_CURRENT=$(echo $CURRENT_METRICS | jq -r '.[] | select(.metric == "complexity") | .value')
          CYCLO_TARGET=$(echo $TARGET_METRICS | jq -r '.[] | select(.metric == "complexity") | .value')
          CYCLO_DIFF=$((CYCLO_CURRENT - CYCLO_TARGET))
          
          COG_CURRENT=$(echo $CURRENT_METRICS | jq -r '.[] | select(.metric == "cognitive_complexity") | .value')
          COG_TARGET=$(echo $TARGET_METRICS | jq -r '.[] | select(.metric == "cognitive_complexity") | .value')
          COG_DIFF=$((COG_CURRENT - COG_TARGET))
          
          # コメントを生成
          COMMENT="## SonarCloud Complexity Metrics

          ### Cyclomatic Complexity
          - Current: $CYCLO_CURRENT
          - Target: $CYCLO_TARGET
          - Difference: $CYCLO_DIFF

          ### Cognitive Complexity
          - Current: $COG_CURRENT
          - Target: $COG_TARGET
          - Difference: $COG_DIFF"
          
          echo "$COMMENT" > comment.txt
                
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('comment.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
