name: SonarCloud Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
            
      - name: Generate and post detailed metrics comment
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          CURRENT_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          # 変更のあったファイルのメトリクスを取得
          CURRENT_FILES=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/measures/component_tree?component=${PROJECT_KEY}&branch=${CURRENT_BRANCH}&qualifiers=FIL&metricKeys=complexity,cognitive_complexity,function_complexity,duplicated_lines_density,lines" | jq -r '.components[]')
          
          # ターゲットブランチのファイルメトリクスを取得
          TARGET_FILES=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/measures/component_tree?component=${PROJECT_KEY}&branch=${BASE_BRANCH}&qualifiers=FIL&metricKeys=complexity,cognitive_complexity,function_complexity,duplicated_lines_density,lines" | jq -r '.components[]')

          # 初期化
          CYCLO_DIFF=0
          COG_DIFF=0

          # 差分を計算
          for FILE in $(echo "$CURRENT_FILES" | jq -r '.key'); do
            # 現在のブランチのファイルメトリクス
            CURRENT_METRICS=$(echo "$CURRENT_FILES" | jq -r "select(.key == \"$FILE\") | .measures | from_entries")
            CURRENT_CYCLO=$(echo "$CURRENT_METRICS" | jq -r '.complexity // 0')
            CURRENT_COG=$(echo "$CURRENT_METRICS" | jq -r '.cognitive_complexity // 0')

            # マージ先ブランチのファイルメトリクス
            TARGET_METRICS=$(echo "$TARGET_FILES" | jq -r "select(.key == \"$FILE\") | .measures | from_entries")
            TARGET_CYCLO=$(echo "$TARGET_METRICS" | jq -r '.complexity // 0')
            TARGET_COG=$(echo "$TARGET_METRICS" | jq -r '.cognitive_complexity // 0')

            # 差分を加算
            CYCLO_DIFF=$((CYCLO_DIFF + CURRENT_CYCLO - TARGET_CYCLO))
            COG_DIFF=$((COG_DIFF + CURRENT_COG - TARGET_COG))
          done

          # コメントを生成
          COMMENT="## SonarCloud Complexity Metrics

          ### Cyclomatic Complexity
          - Difference: $CYCLO_DIFF

          ### Cognitive Complexity
          - Difference: $COG_DIFF"
          
          echo "$COMMENT" > comment.txt
                
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('comment.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
